### ISSUE TITLE
Tutorial 1 Inconsistencies 

### ISSUE THREAD

**Issue by jesshanh210** [csiro-robotics/dynamixel_interface#1]
Hello!

The "Tutorial 1: Using the controller" shows how to create a config file however, this is inconsistent with the example config file provided in config/ folder. For example: init, min and max are different from zero_pos, min_pos and max_pos (see below).

In the tutorial:
```
servos:
        - id: 1                   # (ID set in servo eeprom, must be unique on this port)
          joint_name: joint_1     # (MUST BE UNIQUE ACROSS ALL PORTS)
          init: 2048              # initial (0 rad) servo position (in raw encoder count)
          min: 0                  # minimum servo position (in raw encoder count)
          max: 4095               # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
```

In the config/ folder:

```
servos:
      - id: 1                   # (ID set in servo eeprom, must be unique on this port)
        joint_name: joint_1     # (MUST BE UNIQUE ACROSS ALL PORTS)
        zero_pos: 2048              # 0 rad servo position (in raw encoder count)
        min_pos: 0                  # minimum servo position (in raw encoder count)
        max_pos: 4095               # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
```

I believe we should use the config/ folder example to model our own config files and if this is the case, can the tutorial be updated accordingly?

Also, I believe the tutorial launch file is also incorrect, since it references a `pkg="dynamixel_interface_controller"`. Should this instead be `pkg="dynamixel_interface"`? 

Thanks!
